[assembly: System.Reflection.AssemblyTitle("JsonLogic.Net.dll")]
[assembly: System.Reflection.AssemblyDescription("Fork of yavuztor's .Net implementation of jsonlogic.com")]
[assembly: System.Reflection.AssemblyVersion("0.0.1")]
[assembly: System.Reflection.AssemblyProduct("jsonlogic.com")]
[assembly: System.Reflection.AssemblyCompany("yavuztor@hotmail.com")]
